Repository appvia/kore, pull requests merged in 2020-02, with the labels that each got.

#24 Docker Push
  .circleci/config.yml
Labels: bug

#26 API Fix Up
  pkg/apiserver/teams.go
  swagger.json
Labels: bug

#30 Authorized Master CIDR
  pkg/hub/assets/plans.go
Labels: bug, enhancement

#29 Deployment files
  .gitignore
  deploy/kube/api.yml
  deploy/kube/apiserver.yml
  deploy/kube/dex.yml
  deploy/kube/etcd.yml
  deploy/kube/mariadb.yml
  deploy/kube/portal.yml
  deploy/kube/redis.yml
Labels: documentation, enhancement

#35 User Fix
  pkg/services/users/teams.go
  pkg/services/users/users.go
  pkg/services/users/users_test.go
Labels: bug

#36 Fix Dex Demo
  pkg/controllers/management/bootstrap/reconcile.go
Labels: bug

#39 Swagger Drift
  .circleci/config.yml
Labels: enhancement

#38 Kubernetes Types
  deploy/crds/clusters.compute.hub.appvia.io_kubernetes.yaml
  pkg/apis/clusters/v1/kubernetes_types.go
  pkg/apis/clusters/v1/zz_generated.deepcopy.go
  pkg/apis/clusters/v1/zz_generated_openapi.go
  pkg/register/assets.go
Labels: bug

#42 CircleCI Build
  .circleci/config.yml
Labels: bug

#43 Namespace claim
  Makefile
  deploy/crds/apps.kore.appvia.io_appdeployments.yaml
  deploy/crds/apps.kore.appvia.io_installplans.yaml
  deploy/crds/aws.compute.kore.appvia.io_awscredentials.yaml
  deploy/crds/aws.compute.kore.appvia.io_eksclusters.yaml
  deploy/crds/clusters.compute.kore.appvia.io_kubernetes.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedclusterrole.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedclusterrolebinding.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedconfig.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedpodsecuritypoliies.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedrole.yaml
  deploy/crds/clusters.compute.kore.appvia.io_namespaceclaims.yaml
  deploy/crds/clusters.compute.kore.appvia.io_namespacepolicy.yaml
  deploy/crds/config.kore.appvia.io_allocations.yaml
  deploy/crds/config.kore.appvia.io_plans.yaml
  deploy/crds/core.kore.appvia.io_idp.yaml
  deploy/crds/core.kore.appvia.io_oidclient.yaml
  deploy/crds/gke.compute.kore.appvia.io_gkecredentials.yaml
  deploy/crds/gke.compute.kore.appvia.io_gkes.yaml
  deploy/crds/org.kore.appvia.io_members.yaml
  deploy/crds/org.kore.appvia.io_teaminvitations.yaml
  deploy/crds/org.kore.appvia.io_teams.yaml
  deploy/crds/org.kore.appvia.io_users.yaml
  hack/setup/instances/claim.yaml
  hack/setup/instances/gke-cluster.yml
  pkg/apis/clusters/v1/namespaceclaim_types.go
  pkg/apis/clusters/v1/zz_generated.deepcopy.go
  pkg/apis/clusters/v1/zz_generated_openapi.go
  pkg/controllers/helper.go
  pkg/controllers/management/bootstrap/reconcile.go
  pkg/controllers/management/clusterroles/reconcile.go
  pkg/controllers/management/namespaceclaims/controller.go
  pkg/controllers/management/namespaceclaims/delete.go
  pkg/controllers/management/namespaceclaims/helpers.go
  pkg/controllers/management/namespaceclaims/reconcile.go
  pkg/controllers/management/namespaceclaims/types.go
  pkg/controllers/management/podpolicy/reconcile.go
  pkg/controllers/register/register.go
  pkg/kore/assets/cluster_roles.yml
  pkg/kore/assets/roles.go
  pkg/kore/hub.go
  pkg/kore/setup.go
  pkg/register/assets.go
Labels: enhancement

#44 Bootstrap demo fix
  pkg/controllers/management/bootstrap/reconcile.go
Labels: bug, enhancement

#37 No Implementation
  pkg/apiserver/apiserver.go
  pkg/apiserver/filters/not_implemented.go
Labels: enhancement

#49 Dex Scope Check
  pkg/kore/config.go
Labels: enhancement

#50 Namespace Claims
  deploy/crds/clusters.compute.kore.appvia.io_kubernetes.yaml
  deploy/crds/clusters.compute.kore.appvia.io_namespaceclaims.yaml
  pkg/apis/clusters/v1/kubernetes_types.go
  pkg/apis/clusters/v1/namespaceclaim_types.go
  pkg/apis/clusters/v1/zz_generated.deepcopy.go
  pkg/apis/clusters/v1/zz_generated_openapi.go
  pkg/apiserver/namespaces.go
  pkg/apiserver/teams.go
  pkg/kore/namespaces.go
  pkg/kore/team.go
  pkg/register/assets.go
Labels: enhancement

#52 Namespace Status
  pkg/controllers/management/namespaceclaims/reconcile.go
Labels: enhancement

#51 Delete by Hand
  pkg/cmd/korectl/delete.go
Labels: enhancement

#53 GKE Fix up
  pkg/kore/gke.go
Labels: bug

#54 Cluster Delete Fix
  pkg/kore/clusters.go
Labels: bug

#56 Clean Up Notfound
  pkg/apiserver/helpers.go
  pkg/cmd/korectl/requestor.go
Labels: bug

#57 Dex Example Deployment Config
  deploy/kube/dex-secret.example.yml
  deploy/kube/dex.kubeconfig.example.yml
Labels: documentation

#58 Audit & Users Merge
  .circleci/config.yml
  cmd/kore-apiserver/options/options.go
  cmd/kore-apiserver/server.go
  pkg/kore/clusters.go
  pkg/kore/gke.go
  pkg/kore/hub.go
  pkg/kore/plans.go
  pkg/kore/teams.go
  pkg/kore/types.go
  pkg/kore/users.go
  pkg/server/server.go
  pkg/server/types.go
  pkg/services/audit/audit.go
  pkg/services/audit/audit_test.go
  pkg/services/audit/config.go
  pkg/services/audit/config_test.go
  pkg/services/audit/doc.go
  pkg/services/audit/fake/audit.go
  pkg/services/audit/filter.go
  pkg/services/audit/filter_options.go
  pkg/services/audit/fixtures/db.yml
  pkg/services/audit/model/migration.go
  pkg/services/audit/types.go
  pkg/services/users/audit.go
  pkg/services/users/audit_entry.go
  pkg/services/users/audit_options.go
  pkg/services/users/audit_test.go
  pkg/services/users/filter_options.go
  pkg/services/users/model/audit.go
  pkg/services/users/model/migration.go
  pkg/services/users/store.go
  pkg/services/users/store_test.go
  pkg/services/users/types.go
Labels: enhancement

#59 Resource Registration
  pkg/server/schema.go
  pkg/server/server.go
Labels: enhancement

#61 Remove Kube Files
  deploy/kube/sso/database.yml
  deploy/kube/sso/deployment.yml
  deploy/kube/sso/gossip.yml
  deploy/kube/sso/ingress.yml
Labels: documentation

#62 Fix Options
  cmd/kore-apiserver/server.go
Labels: bug

#63 Audit Events
  pkg/apis/org/v1/audit_event_types.go
  pkg/apis/org/v1/zz_generated.deepcopy.go
  pkg/apis/org/v1/zz_generated_register.go
  pkg/apiserver/audit.go
  pkg/apiserver/teams.go
  pkg/apiserver/types/types.go
  pkg/cmd/korectl/get.go
  pkg/cmd/korectl/helper.go
  pkg/kore/audit.go
  pkg/kore/codec.go
  pkg/kore/plans.go
  pkg/kore/team.go
  pkg/kore/teams.go
  pkg/server/schema.go
  pkg/services/users/audit_entry.go
  pkg/services/users/audit_test.go
  pkg/services/users/filter.go
  pkg/services/users/filter_options.go
Labels: enhancement

#65 Fix Race
  pkg/kore/teams.go
Labels: bug

#66 Auth proxy
  Makefile
  cmd/auth-proxy/main.go
  cmd/auth-proxy/options/options.go
  go.mod
  go.sum
  images/Dockerfile.auth-proxy
  images/Dockerfile.kore-apiserver
  pkg/apiserver/login.go
  pkg/cmd/auth-proxy/config.go
  pkg/cmd/auth-proxy/keys.go
  pkg/cmd/auth-proxy/server.go
  pkg/cmd/auth-proxy/types.go
  pkg/controllers/management/kubernetes/proxy.go
  pkg/utils/certificates/public_key.go
  pkg/utils/certificates/public_key_test.go
  pkg/utils/jwt.go
  pkg/utils/openid/jwks.go
  pkg/utils/openid/jwks_test.go
  pkg/version/version.go
Labels: enhancement

#69 K8s creds
  hack/setup/org.yaml
  hack/setup/team.yml
  pkg/apis/clusters/v1/kubernetes_credentials_types.go
  pkg/apis/clusters/v1/zz_generated.deepcopy.go
  pkg/apiserver/k8s_credentials.go
  pkg/apiserver/teams.go
  pkg/controllers/cloud/gcp/gke/bootstrap.go
  pkg/controllers/management/bootstrap/reconcile.go
  pkg/kore/k8s_credentials.go
  pkg/kore/team.go
Labels: enhancement

#68 Readme
  README.md
  deploy/kube/README.md
  doc/architecture.md
  doc/global-configuration.md
  doc/images/kore_admin_flow.svg
  doc/images/kore_dev_flow.svg
  doc/quick-start.md
  doc/user-management.md
  doc/users.md
  hack/compose/demo.yml
Labels: documentation

#76 User Claims
  cmd/kore-apiserver/options/options.go
  pkg/apiserver/login.go
Labels: bug, enhancement

#77 Discovery URL
  cmd/kore-apiserver/server.go
Labels: enhancement

#73 Discovery URL
  pkg/controllers/management/bootstrap/assets.go
  pkg/controllers/management/bootstrap/reconcile.go
  pkg/utils/openid/discovery.go
  pkg/utils/openid/types.go
Labels: enhancement

#79 User Claims
  pkg/controllers/management/kubernetes/proxy.go
  pkg/utils/jwt.go
Labels: bug, enhancement

#80 Authentication Proxy
  pkg/cmd/auth-proxy/server.go
  pkg/cmd/auth-proxy/types.go
  pkg/controllers/management/kubernetes/proxy.go
  pkg/utils/jwt.go
Labels: bug

#81 Kubernetes Creds
  pkg/controllers/cloud/gcp/gke/bootstrap.go
  pkg/kore/k8s_credentials.go
Labels: bug

#85 Fix typo
  pkg/kore/clusters.go
Labels: bug

#88 Feature Gating Bootstrap
  cmd/kore-apiserver/options/options.go
  pkg/controllers/management/bootstrap/controller.go
  pkg/kore/types.go
Labels: enhancement

#96 Cluster Role Bindings
  pkg/utils/kubernetes/bindings.go
Labels: bug

#97 Auth proxy metrics
  cmd/auth-proxy/main.go
  cmd/auth-proxy/options/options.go
  pkg/cmd/auth-proxy/metrics.go
  pkg/cmd/auth-proxy/server.go
  pkg/cmd/auth-proxy/types.go
  pkg/controllers/management/kubernetes/proxy.go
Labels: enhancement

#99 Fix Debug Message
  pkg/apiserver/login.go
Labels: bug

#94 Demo Files
  .gitignore
  demo.env
  doc/quick-start.md
  hack/compose/demo.yml
Labels: documentation, enhancement

#102 Controller Registration
  pkg/server/server.go
Labels: enhancement

#105 Namespace Claim Fix
  pkg/controllers/management/namespaceclaims/controller.go
  pkg/controllers/management/namespaceclaims/reconcile.go
Labels: bug, enhancement

#115 Docker Images
  .circleci/config.yml
  Dockerfile
  Makefile
  images/Dockerfile.kore-apiserver
Labels: enhancement

#117 Credentials
  examples/gke-cluster.yml
  pkg/controllers/management/kubernetes/reconcile.go
Labels: bug

#119 Enable Network Policies for GKE
  pkg/controllers/cloud/gcp/gke/gke_client.go
Labels: bug

#120 - fixing the debug message
  pkg/controllers/management/clusterconfig/reconcile.go
Labels: bug

#125 Fix Cluster Config Params
  pkg/controllers/management/clusterconfig/reconcile.go
Labels: enhancement

#124 GKE Plans
  pkg/kore/assets/plans.go
Labels: enhancement

#128 GKE Cloud NAT
  pkg/controllers/cloud/gcp/gke/gke_client.go
Labels: bug

#131 Reconcile GKE
  pkg/controllers/cloud/gcp/gke/gke_client.go
  pkg/controllers/cloud/gcp/gke/reconcile.go
Labels: enhancement

#110 Move clusterman out of bootstrap controller
  .circleci/config.yml
  Makefile
  cmd/kore-clusterappman/main.go
  cmd/kore-clusterappman/options/options.go
  cmd/kore-clusterappman/server.go
  doc/kore-development/clusterappman.md
  hack/generate/manifests_vfsdata.go
  images/Dockerfile.kore-apiserver
  pkg/clusterappman/.gitignore
  pkg/clusterappman/clusterappman.go
  pkg/clusterappman/config.go
  pkg/clusterappman/helpers.go
  pkg/clusterappman/helpers_test.go
  pkg/clusterappman/manifests.go
  pkg/clusterappman/manifests/application-controller/README.md
  pkg/clusterappman/manifests/application-controller/application-all.yaml
  pkg/clusterappman/manifests/captain/README.md
  pkg/clusterappman/manifests/captain/captain-application.yaml
  pkg/clusterappman/manifests/captain/captain.yaml
  pkg/clusterappman/manifests/captain/clusterrolebinding.yaml
  pkg/clusterappman/manifests/kore-helm-repo/application-all.yaml
  pkg/clusterappman/manifests_generater.go
  pkg/clusterappman/types.go
  pkg/clusterman/config.go
  pkg/controllers/management/bootstrap/assets.go
  pkg/controllers/management/bootstrap/controller.go
  pkg/controllers/management/bootstrap/delete.go
  pkg/controllers/management/bootstrap/helpers.go
  pkg/controllers/management/bootstrap/reconcile.go
  pkg/controllers/management/kubernetes/clusterappman.go
  pkg/controllers/management/kubernetes/helper.go
  pkg/controllers/management/kubernetes/reconcile.go
  pkg/controllers/management/kubernetes/types.go
  pkg/controllers/register/register.go
Labels: enhancement

#132 Spelling Checks
  Makefile
Labels: enhancement

#140 Fix user invitation
  examples/user.yml
  pkg/apiserver/helpers.go
  pkg/apiserver/teams.go
  pkg/kore/codec.go
  pkg/kore/members.go
  pkg/services/users/invitations.go
Labels: bug

#141 Operators
  Makefile
Labels: cleanup

#142 Multi Docs Files
  examples/allocation.yml
  examples/credentials.yml
  examples/gke.yml
  examples/kubernetes.yml
  go.mod
  go.sum
  pkg/cmd/korectl/helper.go
Labels: bug

#154 Spelling Fix
  Makefile
  deploy/kube/README.md
  doc/kore-development/clusterappman.md
  pkg/apis/apps/v1/app_deployment_types.go
  pkg/apis/clusters/v1/managed_cluster_role_binding_types.go
  pkg/clusterapp/clusterapp.go
  pkg/clusterapp/helpers.go
  pkg/clusterappman/clusterappman.go
  pkg/clusterappman/helpers.go
  pkg/clusterappman/manifests/application-controller/README.md
  pkg/cmd/korectl/auth.go
  pkg/controllers/apps/deployments/reconcile.go
  pkg/controllers/cloud/gcp/gke/gke_client.go
  pkg/controllers/cloud/gcp/gke/reconcile.go
  pkg/controllers/cloud/gcp/gkecredentials/reconcile.go
  pkg/controllers/helper.go
  pkg/controllers/management/clusterbindings/controller.go
  pkg/controllers/management/clusterroles/controller.go
  pkg/controllers/management/kubernetes/reconcile.go
  pkg/controllers/management/podpolicy/helper.go
  pkg/controllers/management/podpolicy/reconcile.go
  pkg/controllers/user/allocations/reconcile.go
  pkg/controllers/user/teams/reconcile.go
  pkg/kore/hub.go
  pkg/server/server.go
  pkg/services/users/filter.go
  pkg/services/users/members.go
  pkg/services/users/store.go
  pkg/services/users/types.go
  pkg/store/store.go
  pkg/store/types.go
  pkg/utils/openid/discovery.go
  pkg/utils/plural.go
Labels: bug

#159 Makefile Exit
  Makefile
Labels: bug

#156 Remove crds
  .gitignore
  deploy/crds/apps.kore.appvia.io_appdeployments.yaml
  deploy/crds/apps.kore.appvia.io_installplans.yaml
  deploy/crds/aws.compute.kore.appvia.io_awscredentials.yaml
  deploy/crds/aws.compute.kore.appvia.io_eksclusters.yaml
  deploy/crds/clusters.compute.kore.appvia.io_kubernetes.yaml
  deploy/crds/clusters.compute.kore.appvia.io_kubernetescredentials.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedclusterrole.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedclusterrolebinding.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedconfig.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedpodsecuritypoliies.yaml
  deploy/crds/clusters.compute.kore.appvia.io_managedrole.yaml
  deploy/crds/clusters.compute.kore.appvia.io_namespaceclaims.yaml
  deploy/crds/clusters.compute.kore.appvia.io_namespacepolicy.yaml
  deploy/crds/config.kore.appvia.io_allocations.yaml
  deploy/crds/config.kore.appvia.io_plans.yaml
  deploy/crds/core.kore.appvia.io_idp.yaml
  deploy/crds/core.kore.appvia.io_oidclient.yaml
  deploy/crds/gke.compute.kore.appvia.io_gkecredentials.yaml
  deploy/crds/gke.compute.kore.appvia.io_gkes.yaml
  deploy/crds/org.kore.appvia.io_members.yaml
  deploy/crds/org.kore.appvia.io_teaminvitations.yaml
  deploy/crds/org.kore.appvia.io_teams.yaml
  deploy/crds/org.kore.appvia.io_users.yaml
Labels: cleanup

#157 TLS on API
  pkg/apiserver/apiserver.go
Labels: enhancement

#158 Enable Handler
  pkg/apiserver/apiserver.go
  pkg/apiserver/types.go
Labels: enhancement

#166 Example Cluster
  doc/quick-start.md
  examples/gke.yml
Labels: documentation

#169 Bumping demo
  hack/compose/demo.yml
  pkg/kore/assets/plans.go
Labels: bug

#171 Docs
  doc/quick-start.md
Labels: documentation

#60 CLI Context
  cmd/korectl/main.go
  pkg/cmd/korectl/auth.go
  pkg/cmd/korectl/commands.go
  pkg/cmd/korectl/config.go
  pkg/cmd/korectl/contexts.go
  pkg/cmd/korectl/helper.go
  pkg/cmd/korectl/kubeconfig.go
  pkg/cmd/korectl/requestor.go
  pkg/cmd/korectl/types.go
Labels: enhancement

#173 don't worry about the small generated additions
  go.mod
  go.sum
Labels: bug

#167 Golang Arch
  Makefile
Labels: bug

#178 Revert "CLI Context"
  cmd/korectl/main.go
  pkg/cmd/korectl/auth.go
  pkg/cmd/korectl/commands.go
  pkg/cmd/korectl/config.go
  pkg/cmd/korectl/contexts.go
  pkg/cmd/korectl/helper.go
  pkg/cmd/korectl/kubeconfig.go
  pkg/cmd/korectl/requestor.go
  pkg/cmd/korectl/types.go
Labels: bug

#186 Fix Struct Fields
  pkg/cmd/korectl/types.go
Labels: bug

#195 Cluster Deletion
  cmd/kore-apiserver/options/options.go
  cmd/kore-apiserver/server.go
  go.mod
  go.sum
  pkg/apis/core/v1/status_types.go
  pkg/controllers/management/kubernetes/delete.go
  pkg/controllers/management/kubernetes/proxy.go
  pkg/controllers/management/kubernetes/reconcile.go
  pkg/kore/types.go
Labels: enhancement

#199 Dropping Early Status
  pkg/controllers/management/kubernetes/reconcile.go
Labels: bug

#198 Demo Bump
  hack/compose/demo.yml
Labels: enhancement

#213 Auth Proxy
  pkg/cmd/auth-proxy/server.go
Labels: bug

#215 Proxy Release
  pkg/controllers/management/kubernetes/proxy.go
Labels: enhancement

#217 Fixing Nameclaim & Audit Event
  pkg/apis/apps/v1/zz_generated_openapi.go
  pkg/apis/clusters/v1/namespaceclaim_types.go
  pkg/apis/clusters/v1/zz_generated_openapi.go
  pkg/apis/core/v1/zz_generated.deepcopy.go
  pkg/apis/org/v1/audit_event_types.go
  pkg/register/assets.go
Labels: bug

#218 Korectl Auth
  pkg/cmd/korectl/auth.go
Labels: bug, cleanup
