Repository appvia/kore, pull requests merged in 2020-04, with the labels that each got.

#463 Kubernetes Images
  .circleci/config.yml
  hack/compose/kube.yml
Labels: enhancement

#467 Release Master to QA
  .circleci/config.yml
  .gitignore
  charts/kore/templates/ingress.yaml
  charts/kore/templates/kore.yml
  charts/kore/templates/portal.yml
  charts/kore/templates/secret.yaml
  charts/kore/values.yaml
  hack/compose/ui.yml
  hack/deploy-qa.sh
  hack/json2yaml.rb
  hack/verify-swagger.sh
  hack/yaml2json.rb
Labels: EPIC: releases, enhancement

#472 QA Release Deps
  .circleci/config.yml
Labels: cleanup

#471 Kore E2E Checks
  .gitignore
  cmd/auth-proxy/main.go
  cmd/kore-apiserver/main.go
  cmd/kore-clusterappman/main.go
  examples/user.yml
  pkg/controllers/management/clusterconfig/reconcile.go
  pkg/controllers/management/clusterroles/controller.go
  pkg/controllers/management/kubernetes/delete.go
  pkg/controllers/management/kubernetes/ensure.go
  pkg/kore/gkecredentials.go
  pkg/kore/users.go
  test/e2e/README.md
  test/e2e/check-e2e.sh
  test/e2e/check-suite-units.sh
  test/e2e/check-suite.sh
  test/e2e/environment.sh
  test/e2e/integration/auth-proxy.bats
  test/e2e/integration/clusterappman.bats
  test/e2e/integration/clusterconfig.bats
  test/e2e/integration/clusterroles.bats
  test/e2e/integration/gke-credentials.bats
  test/e2e/integration/gke-deletion.bats
  test/e2e/integration/gke.bats
  test/e2e/integration/helper.bash
  test/e2e/integration/namespaces.bats
  test/e2e/integration/plans.bats
  test/e2e/integration/profiles.bats
  test/e2e/integration/safeguards.bats
  test/e2e/integration/setup.bats
  test/e2e/integration/teams.bats
  test/e2e/integration/teardown.bats
  test/e2e/integration/users.bats
  test/e2e/integration/whoami.bats
Labels: EPIC: releases, enhancement

#462 GKE Kubernetes Version
  pkg/kore/assets/plans.go
Labels: enhancement

#480 Admin User Check
  test/e2e/integration/users.bats
Labels: cleanup

#483 Create & Delete Admin
  pkg/cmd/korectl/create.go
  pkg/cmd/korectl/create_admin.go
  pkg/cmd/korectl/create_member.go
  pkg/cmd/korectl/delete.go
  pkg/cmd/korectl/delete_admin.go
  pkg/kore/members.go
  test/e2e/integration/users.bats
Labels: enhancement

#490 Oauth Redirect URL Bug Fix
  pkg/apiserver/login.go
Labels: bug

#519 EKS Master Security Group
  pkg/apiclient/models/v1alpha1_e_k_s_spec.go
  pkg/apis/eks/v1alpha1/ekscluster_types.go
  pkg/apis/eks/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/eks/v1alpha1/zz_generated_openapi.go
  pkg/cmd/korectl/helper.go
  pkg/controllers/cloud/aws/eks/reconcile.go
  pkg/controllers/cloud/aws/eksvpc/delete.go
  pkg/kore/assets/plan_schema_eks.go
  pkg/kore/assets/plan_schema_eks_test.go
  pkg/kore/assets/plans.go
  pkg/register/assets.go
  pkg/utils/cloud/aws/eks.go
  ui/kore-api-swagger.json
Labels: EPIC: eks

#530 Namespace Delete Bug
  pkg/controllers/management/namespaceclaims/delete.go
  test/e2e/integration/namespaces.bats
Labels: bug

#527 EKS Improvements
  cmd/kore-apiserver/options/options.go
  cmd/kore-apiserver/server.go
  pkg/apiclient/models/v1alpha1_e_k_s_node_group_status.go
  pkg/apiclient/models/v1alpha1_e_k_s_status.go
  pkg/apis/eks/v1alpha1/ekscluster_types.go
  pkg/apis/eks/v1alpha1/eksnodegroup_types.go
  pkg/apis/eks/v1alpha1/zz_generated_openapi.go
  pkg/controllers/bootstrap.go
  pkg/controllers/cloud/aws/eks/controller.go
  pkg/controllers/cloud/aws/eks/delete.go
  pkg/controllers/cloud/aws/eks/ensure.go
  pkg/controllers/cloud/aws/eks/reconcile.go
  pkg/controllers/cloud/aws/eksnodegroup/controller.go
  pkg/controllers/cloud/aws/eksnodegroup/delete.go
  pkg/controllers/cloud/aws/eksnodegroup/ensure.go
  pkg/controllers/cloud/aws/eksnodegroup/reconcile.go
  pkg/controllers/cloud/aws/eksvpc/delete.go
  pkg/controllers/cloud/aws/eksvpc/reconcile.go
  pkg/controllers/cloud/gcp/gke/delete.go
  pkg/controllers/helper.go
  pkg/controllers/management/cluster/controller_test.go
  pkg/controllers/management/cluster/delete.go
  pkg/controllers/management/cluster/helper.go
  pkg/controllers/management/cluster/reconcile.go
  pkg/controllers/management/clusterroles/reconcile.go
  pkg/controllers/management/kubernetes/delete.go
  pkg/controllers/management/kubernetes/reconcile.go
  pkg/controllers/secrets.go
  pkg/controllers/types.go
  pkg/kore/types.go
  pkg/register/assets.go
  pkg/utils/cloud/aws/aws.go
  pkg/utils/cloud/aws/eks.go
  pkg/utils/cloud/aws/iam.go
  pkg/utils/cloud/aws/vpc_client.go
  pkg/utils/kubernetes/client.go
  pkg/utils/kubernetes/ensure.go
  pkg/utils/kubernetes/finalizers.go
  ui/kore-api-swagger.json
Labels: EPIC: eks

#545 Fix Default Team Suggestion
  pkg/cmd/kore/kore.go
Labels: enhancement

#551 Default Team
  pkg/cmd/kore/kore.go
  pkg/cmd/utils/handler.go
Labels: enhancement

#535 GKE Reconciliation Loop
  pkg/controllers/cloud/gcp/gke/delete.go
  pkg/controllers/cloud/gcp/gke/gke_client.go
  pkg/controllers/cloud/gcp/gke/reconcile.go
  pkg/utils/structs.go
  pkg/utils/structs_test.go
Labels: enhancement

#544 EKS Updates
  pkg/apiclient/models/v1alpha1_e_k_s_node_group_spec.go
  pkg/apis/eks/v1alpha1/eksnodegroup_types.go
  pkg/apis/eks/v1alpha1/zz_generated_openapi.go
  pkg/controllers/cloud/aws/eksnodegroup/delete.go
  pkg/controllers/cloud/aws/eksnodegroup/ensure.go
  pkg/controllers/cloud/aws/eksnodegroup/reconcile.go
  pkg/register/assets.go
  pkg/utils/cloud/aws/eks.go
  pkg/utils/pointers.go
  ui/kore-api-swagger.json
Labels: enhancement

#568 Active Profile
  pkg/cmd/kore/profiles/list.go
  pkg/utils/render/format.go
Labels: enhancement

#569 Method Not Allowed
  pkg/cmd/errors/errors.go
  pkg/cmd/utils/factory.go
Labels: enhancement

#583 Credentials Check
  pkg/controllers/cloud/aws/eksvpc/delete.go
Labels: bug

#589 E2E Workflow
  .circleci/config.yml
  Makefile
  images/Dockerfile.auth-proxy
  images/Dockerfile.kore-apiserver
  pkg/store/update.go
  test/README.md
  test/e2e/check-suite.sh
  test/e2e/environment.sh
  test/e2e/integration/auth-proxy.bats
  test/e2e/integration/gke-credentials.bats
  test/e2e/integration/gke-deletion.bats
  test/e2e/integration/gke.bats
  test/e2e/integration/namespaces.bats
  test/e2e/integration/plans.bats
  test/e2e/integration/safeguards.bats
  test/e2e/integration/teams.bats
  test/e2e/integration/teardown.bats
  test/e2e/integration/whoami.bats
  test/trigger-e2e.sh
Labels: EPIC: releases, enhancement, prototype

#608 Admin Fixes
  .circleci/config.yml
  hack/deploy-qa.sh
  pkg/cmd/kore/create/admin.go
  pkg/cmd/kore/delete/delete_admin.go
  test/e2e/environment.sh
  test/e2e/integration/gke-deletion.bats
  test/e2e/integration/namespaces.bats
  test/e2e/integration/users.bats
Labels: EPIC: releases, enhancement

#601 Get Audit Command & Plural Fix
  pkg/apiclient/operations/list_audit_events_responses.go
  pkg/apiclient/operations/list_team_audit_responses.go
  pkg/apiclient/operations/operations_client.go
  pkg/apiserver/audit.go
  pkg/apiserver/teams.go
  pkg/apiserver/teams_audit_integration_test.go
  pkg/client/client.go
  pkg/cmd/kore/get/audit.go
  pkg/cmd/kore/get/get.go
  pkg/cmd/utils/helper.go
  pkg/cmd/utils/resource_types.go
  pkg/cmd/utils/types.go
  ui/kore-api-swagger.json
  ui/lib/utils/api-paths.js
Labels: bug, enhancement

#612 Replace korectl references with kore in docs
  doc/alpha-local-quick-start.md
  doc/install-kore-in-kind.md
  doc/install.md
  doc/security-gke.md
  pkg/client/config/types.go
  pkg/cmd/kore/create/secret.go
  pkg/cmd/kore/get/get.go
  pkg/cmd/kore/local/local.go
  pkg/cmd/kore/local/logs.go
  pkg/cmd/kore/local/start.go
  pkg/cmd/kore/local/stop.go
  pkg/cmd/kore/login/login.go
  pkg/cmd/kore/profiles/delete.go
  pkg/cmd/kore/profiles/profiles.go
  pkg/cmd/kore/profiles/set.go
  pkg/cmd/kore/profiles/use.go
  ui/README.md
  ui/pages/teams/[name].js
  ui/scripts/run-dev.sh
  ui/scripts/run-prod.sh
Labels: EPIC: kore not korectl, cli, documentation

#626 Fix QA Images
  .circleci/config.yml
  hack/deploy-qa.sh
Labels: EPIC: releases

#602 Kore Token Refresh
  pkg/client/client.go
  pkg/client/fake/client.go
  pkg/client/fake/fake.go
  pkg/client/types.go
  pkg/cmd/kore/get/get_test.go
  pkg/cmd/kore/kore.go
  pkg/cmd/utils/factory.go
  pkg/utils/httputils/client.go
  pkg/utils/jwt.go
  pkg/utils/openid/refresh.go
Labels: cli, enhancement

#641 Get Resources Names for Autocompletion
  pkg/cmd/utils/resource.go
Labels: bug

#662 Replace prompt in kore local configure to use manifoldco/promptui
  pkg/cmd/kore/profiles/configure.go
  pkg/cmd/utils/prompts.go
Labels: bug

#651 Always check on the team API endpoints whether a team exists
  pkg/apiserver/helpers.go
  pkg/apiserver/teams.go
  pkg/store/client.go
Labels: bug

#681 [DOCS] Fixing Examples
  examples/eks-credentials.yml
  examples/eks-vpc.yml
  examples/eks.yml
  examples/gcp-credentials.yml
Labels: documentation

#688 docs: remove alpha text from kore local feature
  README.md
  doc/local-quick-start.md
Labels: documentation

#659 Client Profile Configuration
  pkg/client/client.go
  pkg/client/config/config.go
  pkg/client/helper.go
  pkg/cmd/errors/errors.go
  pkg/cmd/utils/factory.go
  pkg/utils/reflect.go
  pkg/utils/reflect_test.go
Labels: bug

#576 EKS Reconcilation Loop
  .circleci/config.yml
  pkg/controllers/cloud/aws/eks/ensure.go
  pkg/controllers/cloud/aws/eks/reconcile.go
  pkg/controllers/cloud/aws/eksnodegroup/ensure.go
  pkg/utils/cloud/aws/eks.go
  pkg/utils/slices.go
  pkg/utils/slices_test.go
  test/e2e/check-suite.sh
  test/e2e/integration/auth-proxy.bats
  test/e2e/integration/eks.bats
  test/trigger-e2e.sh
Labels: enhancement
