Repository appvia/kore, pull requests merged in 2020-06, with the labels that each got.

#910 Local development improvements
  .gitignore
  Makefile
  doc/install-kore-in-kind.md
  images/Dockerfile.kore-apiserver.dev
  scripts/kind_dev.sh
  ui/Dockerfile.dev
  ui/scripts/run-dev.sh
  ui/scripts/run-prod.sh
  ui/scripts/run-with-env.sh
Labels: enhancement

#917 Kore Autocomplete Fix
  pkg/cmd/kore/get/servicecredential.go
Labels: bug, cli

#920 Make default plans read-only, keep upgraded. Allow UI to delete plans.
  pkg/kore/assets/plans.go
  pkg/kore/setup.go
  ui/lib/components/plans/PlanItem.js
  ui/lib/components/plans/PlanList.js
  ui/lib/kore-api/kore-api-client.js
Labels: enhancement

#900 Get configuration from secrets for service providers and services
  doc/setting-up-aws-servicebroker.md
  pkg/apiclient/models/v1_configuration_from_source.go
  pkg/apiclient/models/v1_optional_secret_key_selector.go
  pkg/apiclient/models/v1_service_provider_spec.go
  pkg/apiclient/models/v1_service_spec.go
  pkg/apis/core/v1/configuration.go
  pkg/apis/core/v1/zz_generated.deepcopy.go
  pkg/apis/services/v1/service_provider_types.go
  pkg/apis/services/v1/service_types.go
  pkg/apis/services/v1/zz_generated.deepcopy.go
  pkg/apis/services/v1/zz_generated_openapi.go
  pkg/cmd/kore/create/cluster.go
  pkg/cmd/kore/create/service.go
  pkg/cmd/kore/create/servicecredentials.go
  pkg/cmd/kore/patch/patch.go
  pkg/cmd/utils/helper.go
  pkg/kore/service_providers.go
  pkg/kore/services.go
  pkg/register/assets.go
  pkg/serviceproviders/application/delete.go
  pkg/serviceproviders/application/factory.go
  pkg/serviceproviders/application/helper.go
  pkg/serviceproviders/application/reconcile.go
  pkg/serviceproviders/awsservicebroker/factory.go
  pkg/serviceproviders/awsservicebroker/helper.go
  pkg/serviceproviders/awsservicebroker/types.go
  pkg/serviceproviders/dummy.go
  pkg/serviceproviders/openservicebroker/factory.go
  pkg/serviceproviders/openservicebroker/reconcile.go
  pkg/store/store.go
  pkg/store/types.go
  pkg/utils/configuration/configuration_suite_test.go
  pkg/utils/configuration/parse.go
  pkg/utils/configuration/parse_test.go
  pkg/utils/jsonutils/sjson.go
  ui/kore-api-swagger.json
  ui/lib/kore-api/model/V1ConfigurationFromSource.js
  ui/lib/kore-api/model/V1OptionalSecretKeySelector.js
  ui/lib/kore-api/model/V1ServiceProviderSpec.js
  ui/lib/kore-api/model/V1ServiceSpec.js
Labels: EPIC: AWS Cloud Services, cleanup

#934 Quick fix: don't fail horribly if no cluster exists for namespace claim.
  ui/lib/components/teams/service/ServiceBuildForm.js
Labels: bug

#969 Bugfix: Move the built-in app service plans to the application providers
  pkg/controllers/management/kubernetes/aws_autoscaler.go
  pkg/controllers/serviceproviders/reconcile.go
  pkg/kore/service_plans.go
  pkg/kore/service_providers.go
  pkg/serviceproviders/application/application_suite_test.go
  pkg/serviceproviders/application/factory.go
  pkg/serviceproviders/application/plans.go
  pkg/serviceproviders/application/plans_test.go
Labels: bug

#982 Fix EKS Tests
  test/e2e/check-suite-units.sh
  test/e2e/integration/eks.bats
  test/e2e/integration/secrets.bats
Labels: bug

#1008 Refactoring API model usage into one place
  ui/.babelrc
  ui/__tests__/unit/lib/components/credentials/EKSCredentialsForm.test.js
  ui/__tests__/unit/lib/components/credentials/GCPOrganizationsForm.test.js
  ui/__tests__/unit/lib/components/credentials/GKECredentialsForm.test.js
  ui/__tests__/unit/lib/components/forms/NewTeamForm.test.js
  ui/__tests__/unit/lib/components/plans/ManageClusterPlanForm.test.js
  ui/__tests__/unit/lib/components/policies/PolicyForm.test.js
  ui/__tests__/unit/lib/components/teams/cluster/ClusterBuildForm.test.js
  ui/__tests__/unit/lib/kore-api/kore-api-resources.test.js
  ui/__tests__/unit/lib/utils/allocation-helpers.test.js
  ui/lib/components/credentials/EKSCredentialsForm.js
  ui/lib/components/credentials/GCPOrganizationForm.js
  ui/lib/components/credentials/GKECredentialsForm.js
  ui/lib/components/forms/NewTeamForm.js
  ui/lib/components/plans/ManageClusterPlanForm.js
  ui/lib/components/plans/ManageServicePlanForm.js
  ui/lib/components/policies/PolicyForm.js
  ui/lib/components/resources/VerifiedAllocatedResourceForm.js
  ui/lib/components/setup/GCPKoreManagedProjects.js
  ui/lib/components/setup/GCPProjectAutomationSettings.js
  ui/lib/components/teams/cluster/ClusterBuildForm.js
  ui/lib/components/teams/namespace/NamespaceClaimForm.js
  ui/lib/components/teams/service/ApplicationServiceForm.js
  ui/lib/components/teams/service/ServiceBuildForm.js
  ui/lib/components/teams/service/ServiceCredentialForm.js
  ui/lib/kore-api/index.js
  ui/lib/kore-api/kore-api-resources.js
  ui/lib/utils/allocation-helpers.js
  ui/lib/utils/model.js
  ui/package-lock.json
  ui/package.json
Labels: cleanup, ui
