Repository appvia/kore, pull requests merged in 2020-08, with the labels that each got.

#1191 Login Fix
  pkg/client/config/config.go
  pkg/client/config/errors.go
  pkg/cmd/kore/login/login.go
Labels: bug

#1188 Defaulting to latest
  .circleci/config.yml
  Makefile
  hack/verify-release-images.sh
  ui/Makefile
Labels: bug

#1208 Release Fix
  .circleci/config.yml
Labels: bug

#1210 Document Links
  doc/local-quick-start.md
  pkg/cmd/kore/local/destroy.go
Labels: bug, documentation

#1213 Upgrade cloudinfo, fix login tab
  pkg/cmd/kore/login/login.go
  pkg/kore/assets/applications/kore-costs/cloudinfo.yaml
  pkg/kore/assets/applications_vfsdata.go
Labels: EPIC: Costs, cleanup, cli

#1218 Costs tweaks
  charts/kore/templates/kore.yml
  charts/kore/values.yaml
  cmd/kore-apiserver/options/options.go
  cmd/kore-apiserver/server.go
  pkg/apiclient/models/v1beta1_asset.go
  pkg/apiclient/models/v1beta1_asset_list.go
  pkg/apis/costs/v1beta1/cost_types.go
  pkg/cmd/kore/local/chart/zz_helm_chart.go
  pkg/costs/assets.go
  pkg/kore/setup.go
  pkg/kore/types.go
  pkg/persistence/team_assets.go
  ui/kore-api-swagger.json
  ui/lib/kore-api/model/V1beta1Asset.js
  ui/lib/kore-api/model/V1beta1AssetList.js
Labels: EPIC: Costs

#1220 Kore Costs Key
  pkg/controllers/korefeatures/costsfeature.go
  pkg/controllers/secrets/gcp/reconcile.go
  ui/lib/components/credentials/GCPOrganizationForm.js
Labels: bug
