Repository appvia/kore, pull requests merged in 2020-07, with the labels that each got.

#1024 Make kind-dev work even if you use a non-default path for the code.
  scripts/kind_dev.sh
Labels: cleanup

#1075 removing redundant code
  pkg/controllers/cloud/gcp/projectclaim/controller.go
  pkg/controllers/cloud/gcp/projectclaim/delete.go
  pkg/controllers/cloud/gcp/projectclaim/doc.go
  pkg/controllers/cloud/gcp/projectclaim/ensure.go
  pkg/controllers/cloud/gcp/projectclaim/helper.go
  pkg/controllers/cloud/gcp/projectclaim/reconcile.go
  pkg/controllers/cloud/gcp/projectclaim/types.go
Labels: cleanup

#1109 Contribution Doc
  CONTRIBUTING.md
Labels: bug

#1139 Show AKS cluster icon in the cluster list, constrain icon sizes correctly
  ui/lib/components/teams/cluster/Cluster.js
  ui/lib/prototype/components/teams/cluster/Cluster.js
  ui/lib/utils/ui-helpers.js
Labels: bug, ui

#1142 Nightly Builds Fix
  .circleci/config.yml
Labels: bug

#1148 E2E Fixes
  .circleci/config.yml
  pkg/cmd/kore/local/providers/kind/kind.go
  test/e2e/check-suite.sh
Labels: bug

#1160 Set the IAM role component status to successful after creation for the aws service provider
  pkg/serviceproviders/awsservicebroker/factory.go
Labels: bug
