Repository appvia/kore, pull requests merged in 2020-03, with the labels that each got.

#229 Change context
  cmd/korectl/main.go
  pkg/cmd/korectl/auth.go
  pkg/cmd/korectl/config.go
  pkg/cmd/korectl/local.go
  pkg/cmd/korectl/profiles.go
  pkg/cmd/korectl/types.go
Labels: cleanup

#232 Login Command
  cmd/korectl/main.go
  pkg/cmd/korectl/auth.go
  pkg/cmd/korectl/commands.go
  pkg/cmd/korectl/config.go
  pkg/cmd/korectl/helper.go
  pkg/cmd/korectl/login.go
  pkg/cmd/korectl/profiles.go
  pkg/version/authors.go
Labels: enhancement

#237 Demo Bump
  hack/compose/demo.yml
Labels: feature

#233 Asset Images
  cmd/kore-apiserver/options/options.go
  cmd/kore-apiserver/server.go
  pkg/controllers/management/kubernetes/clusterappman.go
  pkg/controllers/management/kubernetes/helper.go
  pkg/controllers/management/kubernetes/proxy.go
  pkg/kore/types.go
Labels: enhancement

#239 Prevent dangerous oauth redirects
  pkg/apiserver/login.go
Labels: bug

#241 Make port used for cli authentication configurable
  pkg/cmd/korectl/login.go
Labels: enhancement

#250 Docker Volumes
  Makefile
Labels: bug

#262 Fix Local Manifest Generation
  pkg/cmd/korectl/localconf.go
  pkg/utils/marshall.go
  pkg/utils/marshall_test.go
Labels: bug

#269 Fix Zero/Nil Items
  pkg/cmd/korectl/requestor.go
Labels: bug

#267 Gke secure options
  go.mod
  go.sum
  pkg/apis/apps/v1/app_deployment_types.go
  pkg/apis/apps/v1/install_plan_types.go
  pkg/apis/apps/v1/zz_generated_openapi.go
  pkg/apis/aws/v1alpha1/eks_cluster_types.go
  pkg/apis/aws/v1alpha1/zz_generated_openapi.go
  pkg/apis/clusters/v1/kubernetes_types.go
  pkg/apis/clusters/v1/managed_cluster_role_binding_types.go
  pkg/apis/clusters/v1/managed_cluster_role_types.go
  pkg/apis/clusters/v1/managed_config_types.go
  pkg/apis/clusters/v1/managed_pod_security_policy_types.go
  pkg/apis/clusters/v1/managed_role_types.go
  pkg/apis/clusters/v1/namespace_policy_types.go
  pkg/apis/clusters/v1/namespaceclaim_types.go
  pkg/apis/clusters/v1/zz_generated_openapi.go
  pkg/apis/config/v1/allocation_types.go
  pkg/apis/config/v1/plan_types.go
  pkg/apis/config/v1/zz_generated_openapi.go
  pkg/apis/core/v1/idp_client_types.go
  pkg/apis/core/v1/idp_types.go
  pkg/apis/core/v1/zz_generated_openapi.go
  pkg/apis/gke/v1alpha1/gke_types.go
  pkg/apis/gke/v1alpha1/gkecredentials_types.go
  pkg/apis/gke/v1alpha1/zz_generated_openapi.go
  pkg/apis/org/v1/team_invitation_types.go
  pkg/apis/org/v1/team_member_types.go
  pkg/apis/org/v1/team_types.go
  pkg/apis/org/v1/user_types.go
  pkg/apis/org/v1/zz_generated_openapi.go
  pkg/controllers/cloud/gcp/gke/gke_client.go
  pkg/kore/assets/plans.go
  pkg/register/assets.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/gopkg.in/yaml.v2/yamlh.go
  vendor/modules.txt
Labels: enhancement

#273 Cloud Provider Check
  cmd/kore-apiserver/options/options.go
  cmd/kore-apiserver/server.go
  pkg/cmd/korectl/create_cluster.go
  pkg/controllers/cloud/gcp/gke/reconcile.go
  pkg/controllers/management/kubernetes/reconcile.go
  pkg/kore/types.go
Labels: enhancement

#274 Label Fix
  pkg/kore/k8s_credentials.go
Labels: bug

#253 Verify GKE Credentials
  pkg/controllers/cloud/gcp/gkecredentials/controller.go
  pkg/controllers/cloud/gcp/gkecredentials/reconcile.go
  pkg/controllers/cloud/gcp/gkecredentials/resource_manager_client.go
  pkg/utils/slices.go
  vendor/google.golang.org/api/cloudresourcemanager/v1beta1/cloudresourcemanager-api.json
  vendor/google.golang.org/api/cloudresourcemanager/v1beta1/cloudresourcemanager-gen.go
  vendor/modules.txt
Labels: enhancement

#276 GKE Resource Config
  pkg/cmd/korectl/resource.go
Labels: enhancement

#272 Requestor improvements and cleanup
  pkg/cmd/korectl/requestor.go
Labels: cleanup, enhancement

#277 Create invite link when adding a non-existing user to a team
  .circleci/config.yml
  cmd/kore-apiserver/options/options.go
  cmd/kore-apiserver/server.go
  deploy/kube/secrets/kore.example.env
  hack/compose/demo.yml
  hack/dex.env
  pkg/apiserver/invitations.go
  pkg/apiserver/teams.go
  pkg/cmd/korectl/invitations.go
  pkg/cmd/korectl/teams.go
Labels: enhancement

#220 Create a helm chart for kore
  .gitignore
  charts/kore/.helmignore
  charts/kore/Chart.yaml
  charts/kore/scripts/loadbalancer_endpoint_detect.sh
  charts/kore/templates/NOTES.txt
  charts/kore/templates/_helpers.tpl
  charts/kore/templates/endpoint_discover.yaml
  charts/kore/templates/kore.yml
  charts/kore/templates/mysql.yaml
  charts/kore/templates/portal.yml
  charts/kore/templates/secret.yaml
  charts/kore/values.yaml
  doc/auth0.md
  doc/install.md
  doc/quick-start.md
Labels: enhancement

#278 CLI improvements
  pkg/cmd/korectl/create.go
  pkg/cmd/korectl/create_cluster.go
  pkg/cmd/korectl/create_namespace.go
  pkg/cmd/korectl/delete.go
  pkg/cmd/korectl/edit.go
  pkg/cmd/korectl/errors.go
  pkg/cmd/korectl/get.go
  pkg/cmd/korectl/helper.go
  pkg/cmd/korectl/requestor.go
  pkg/cmd/korectl/teams.go
Labels: cleanup

#289 Fix Delete
  pkg/cmd/korectl/delete.go
  pkg/cmd/korectl/profiles.go
Labels: bug

#305 Update Plan Version
  pkg/kore/assets/plans.go
Labels: cleanup

#307 Fix an issue causing the api to panic on cluster creation
  pkg/controllers/management/kubernetes/reconcile.go
Labels: bug

#313 Command Line Arguments Reordering
  cmd/korectl/main.go
  cmd/korectl/options/options.go
  pkg/cmd/app.go
  pkg/cmd/app_test.go
  pkg/cmd/korectl/create_cluster.go
  pkg/cmd/korectl/default.go
Labels: bug, cleanup

#290 Demo Bump
  hack/compose/demo.yml
Labels: cleanup

#323 Demo Release
  examples/gke-cluster.yml
  examples/gke.yml
  hack/compose/demo.yml
  pkg/cmd/korectl/create_cluster.go
Labels: cleanup, enhancement

#328 Container Versions
  hack/compose/kube.yml
Labels: cleanup

#329 Quick Start Readme Link
  README.md
Labels: cleanup, documentation

#325 Use the refresh token to refresh expired credentials
  pkg/cmd/korectl/oidc.go
  pkg/cmd/korectl/requestor.go
  pkg/cmd/korectl/types.go
  pkg/utils/jwt.go
Labels: bug, enhancement

#349 Enable APIs
  doc/alpha-local-quick-start.md
Labels: documentation

#331 Improved Auditing
  pkg/apis/org/v1/audit_event_types.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/audit.go
  pkg/apiserver/filters/auditing.go
  pkg/apiserver/health.go
  pkg/apiserver/idp.go
  pkg/apiserver/login.go
  pkg/apiserver/plans.go
  pkg/apiserver/teams.go
  pkg/apiserver/types.go
  pkg/apiserver/users.go
  pkg/apiserver/whoami.go
  pkg/kore/clusters.go
  pkg/kore/codec.go
  pkg/kore/gke.go
  pkg/kore/plans.go
  pkg/kore/teams.go
  pkg/kore/users.go
  pkg/register/assets.go
  pkg/services/users/audit_entry.go
  pkg/services/users/audit_options.go
  pkg/services/users/audit_test.go
  pkg/services/users/filter_options.go
  pkg/services/users/model/audit.go
Labels: enhancement

#133 Kore Team
  pkg/apiserver/filters/members.go
  pkg/kore/helpers.go
  pkg/kore/teams.go
  pkg/kore/users.go
Labels: enhancement, feature

#353 UI Endpoint
  charts/kore/templates/kore.yml
Labels: bug

#355 Demo Bump
  charts/kore/values.yaml
  hack/compose/demo.yml
Labels: documentation

#369 Bug Fix GKE Region
  pkg/controllers/cloud/gcp/gke/gke_client.go
  pkg/controllers/cloud/gcp/gke/reconcile.go
  pkg/controllers/cloud/gcp/gke/types.go
Labels: bug

#370 Potential Segmentation Fault
  pkg/controllers/cloud/gcp/gke/gke_client.go
Labels: bug

#374 Long Description Format
  pkg/cmd/korectl/create_cluster.go
  pkg/cmd/korectl/create_namespace.go
  pkg/cmd/korectl/create_secret.go
Labels: cleanup

#368 GCP IAM Permissions Check
  pkg/controllers/cloud/gcp/gkecredentials/reconcile.go
  pkg/controllers/cloud/gcp/gkecredentials/resource_manager_client.go
  pkg/utils/cloud/gcp/iam.go
Labels: cleanup, enhancement

#373 Profile Delete Command
  cmd/korectl/main.go
  pkg/cmd/app.go
  pkg/cmd/korectl/config.go
  pkg/cmd/korectl/profiles.go
Labels: cleanup, enhancement

#372 Bump Demo
  charts/kore/values.yaml
  hack/compose/demo.yml
Labels: cleanup

#381 WhoAmI Command Rendering Fix
  pkg/cmd/korectl/requestor.go
  pkg/cmd/korectl/whoami.go
Labels: bug

#382 JSONPath Dependency
  go.mod
  go.sum
  pkg/cmd/korectl/clusters.go
  pkg/cmd/korectl/helper.go
  pkg/cmd/korectl/modifiers.go
  pkg/cmd/korectl/requestor.go
  pkg/cmd/korectl/resource.go
  pkg/cmd/korectl/whoami.go
  vendor/github.com/savaki/jq/.gitignore
  vendor/github.com/savaki/jq/LICENSE
  vendor/github.com/savaki/jq/README.md
  vendor/github.com/savaki/jq/doc.go
  vendor/github.com/savaki/jq/op.go
  vendor/github.com/savaki/jq/parse.go
  vendor/github.com/savaki/jq/scanner/any.go
  vendor/github.com/savaki/jq/scanner/array.go
  vendor/github.com/savaki/jq/scanner/as.go
  vendor/github.com/savaki/jq/scanner/bool.go
  vendor/github.com/savaki/jq/scanner/doc.go
  vendor/github.com/savaki/jq/scanner/err.go
  vendor/github.com/savaki/jq/scanner/find_index.go
  vendor/github.com/savaki/jq/scanner/find_key.go
  vendor/github.com/savaki/jq/scanner/find_range.go
  vendor/github.com/savaki/jq/scanner/null.go
  vendor/github.com/savaki/jq/scanner/number.go
  vendor/github.com/savaki/jq/scanner/object.go
  vendor/github.com/savaki/jq/scanner/string.go
  vendor/github.com/savaki/jq/scanner/util.go
  vendor/github.com/tidwall/gjson/.travis.yml
  vendor/github.com/tidwall/gjson/LICENSE
  vendor/github.com/tidwall/gjson/README.md
  vendor/github.com/tidwall/gjson/SYNTAX.md
  vendor/github.com/tidwall/gjson/gjson.go
  vendor/github.com/tidwall/gjson/go.mod
  vendor/github.com/tidwall/gjson/go.sum
  vendor/github.com/tidwall/gjson/logo.png
  vendor/github.com/tidwall/match/.travis.yml
  vendor/github.com/tidwall/match/LICENSE
  vendor/github.com/tidwall/match/README.md
  vendor/github.com/tidwall/match/match.go
  vendor/github.com/tidwall/pretty/.travis.yml
  vendor/github.com/tidwall/pretty/LICENSE
  vendor/github.com/tidwall/pretty/README.md
  vendor/github.com/tidwall/pretty/pretty.go
  vendor/modules.txt
Labels: enhancement

#383 Fix deepcopy-gen
  hack/update-codegen.sh
  pkg/apis/clusters/v1/zz_generated.deepcopy.go
  pkg/apis/org/v1/zz_generated.deepcopy.go
Labels: bug

#384 Kore UI Tag v0.0.6
  charts/kore/values.yaml
  hack/compose/demo.yml
Labels: bug

#375 Team Name Regex
  pkg/kore/helpers.go
  pkg/kore/helpers_test.go
  pkg/kore/teams.go
  pkg/kore/types.go
  pkg/kore/validation/err_validation.go
Labels: bug

#385 Check whether `make apis` was run
  .circleci/config.yml
  Makefile
  pkg/apis/config/v1/zz_generated_openapi.go
  pkg/kore/helpers_test.go
  pkg/register/assets.go
Labels: enhancement

#397 Kore Admin Delete Check
  pkg/kore/teams.go
Labels: bug

#405 fix invalid gke status when no credentials
  pkg/controllers/cloud/gcp/gke/reconcile.go
Labels: bug

#396 Introducing plan policies
  pkg/apis/config/v1/plan_policy_types.go
  pkg/apis/config/v1/zz_generated.deepcopy.go
  pkg/apis/config/v1/zz_generated_openapi.go
  pkg/apis/config/v1/zz_generated_register.go
  pkg/apis/core/v1/ownership_types.go
  pkg/apiserver/plan_policies.go
  pkg/cmd/korectl/create_cluster.go
  pkg/cmd/korectl/delete.go
  pkg/cmd/korectl/errors.go
  pkg/cmd/korectl/get.go
  pkg/cmd/korectl/helper.go
  pkg/cmd/korectl/requestor.go
  pkg/cmd/korectl/resource.go
  pkg/kore/hub.go
  pkg/kore/plan_policies.go
  pkg/kore/plans.go
  pkg/kore/types.go
  pkg/register/assets.go
  pkg/utils/plural.go
  pkg/utils/plural_test.go
  vendor/modules.txt
Labels: enhancement

#406 Apply from Stdin
  pkg/cmd/korectl/apply.go
  pkg/utils/file.go
Labels: enhancement

#409 Makefile Images Stage Fix
  Makefile
Labels: bug

#416 - removing the unrequired file
  1
Labels: bug

#386 CLI Cleanup & Resource Waits
  cmd/korectl/options/options.go
  pkg/cmd/app.go
  pkg/cmd/korectl/create_allocation.go
  pkg/cmd/korectl/create_cluster.go
  pkg/cmd/korectl/create_gcp_organization.go
  pkg/cmd/korectl/create_gcp_projectclaim.go
  pkg/cmd/korectl/create_member.go
  pkg/cmd/korectl/create_namespace.go
  pkg/cmd/korectl/create_secret.go
  pkg/cmd/korectl/create_team.go
  pkg/cmd/korectl/helper.go
  pkg/cmd/korectl/resource.go
  pkg/cmd/korectl/teams.go
Labels: cleanup

#407 Fix Cloud Provider failing state
  pkg/controllers/cloud/gcp/gke/reconcile.go
  pkg/controllers/management/kubernetes/reconcile.go
Labels: bug

#426 Team Removal with Clusters Bug
  pkg/kore/teams.go
Labels: bug

#428 Default Option Value
  cmd/korectl/options/options.go
Labels: bug

#429 No Blocking Env
  cmd/korectl/options/options.go
Labels: enhancement

#431 Fix namespace claim wait
  pkg/cmd/korectl/create_cluster.go
  pkg/cmd/korectl/create_namespace.go
  pkg/cmd/korectl/helper.go
  pkg/controllers/management/namespaceclaims/reconcile.go
  pkg/utils/unstructured.go
Labels: bug

#432 Allow team deletion
  pkg/kore/authentication/types.go
  pkg/kore/identity.go
  pkg/kore/teams.go
Labels: enhancement

#434 Controller Runtime Client GVK
  pkg/kore/clusters.go
  pkg/store/client.go
Labels: bug

#440 Allocation Namespace Bug Fix
  pkg/kore/allocations.go
Labels: bug

#435 Deleting GKE before Cluster Fix
  pkg/kore/gke.go
  pkg/kore/helpers.go
Labels: bug

#452 Fix Max Attempts on Resource Waits
  pkg/cmd/korectl/helper.go
Labels: bug

#454 GKE Bootstrap Fix
  pkg/controllers/cloud/gcp/gke/bootstrap.go
  pkg/controllers/cloud/gcp/gke/reconcile.go
  pkg/controllers/management/kubernetes/reconcile.go
  pkg/controllers/register.go
Labels: bug

#456 Fix secrets
  pkg/cmd/korectl/create_secret.go
  pkg/controllers/secrets/generic/reconcile.go
Labels: bug
