Repository appvia/kore, pull requests merged in 2020-05, with the labels that each got.

#733 Fix team existence checking in the Kore CLI
  pkg/client/helper.go
  pkg/cmd/kore/kore.go
  pkg/cmd/utils/factory.go
  pkg/cmd/utils/handler.go
  pkg/cmd/utils/wait.go
  pkg/utils/reflect.go
Labels: bug

#773 Fix E2E
  test/e2e/integration/gke-credentials.bats
Labels: bug

#785 Security Rules - Context & Client
  pkg/controllers/security/controller.go
  pkg/controllers/security/reconcile.go
  pkg/kore/security.go
  pkg/security/authproxyips.go
  pkg/security/authproxyips_test.go
  pkg/security/rule_helpers.go
  pkg/security/scanner.go
  pkg/security/types.go
Labels: enhancement

#788 Bugfix: make sure the plan schema endpoints work, create two separate endpoints for service plan schemas
  pkg/apiclient/operations/get_plan_schema_parameters.go
  pkg/apiclient/operations/get_plan_schema_responses.go
  pkg/apiclient/operations/get_service_plan_schema_for_kind_parameters.go
  pkg/apiclient/operations/get_service_plan_schema_for_kind_responses.go
  pkg/apiclient/operations/get_service_plan_schema_for_plan_parameters.go
  pkg/apiclient/operations/get_service_plan_schema_for_plan_responses.go
  pkg/apiclient/operations/get_service_plan_schema_parameters.go
  pkg/apiclient/operations/get_service_plan_schema_responses.go
  pkg/apiclient/operations/operations_client.go
  pkg/apiserver/plan_schemas.go
  pkg/apiserver/service_plan_schemas.go
  ui/kore-api-swagger.json
  ui/lib/components/plans/PlanViewer.js
  ui/lib/components/services/ServicePlanForm.js
  ui/lib/kore-api/kore-api-client.js
Labels: bug, important

#805 [BUG] Fix Update Accounting CRD
  pkg/kore/accounts.go
Labels: bug

#811 QA Services Feature Gate
  hack/deploy-qa.sh
Labels: prototype

#792 Dry Runs
  pkg/cmd/kore/create/admin.go
  pkg/cmd/kore/create/cluster.go
  pkg/cmd/kore/create/ekscredential.go
  pkg/cmd/kore/create/gkecredential.go
  pkg/cmd/kore/create/namespace.go
  pkg/cmd/kore/create/secret.go
  pkg/cmd/kore/create/service.go
  pkg/cmd/kore/create/servicecredentials.go
  pkg/cmd/kore/create/team.go
  pkg/cmd/kore/create/user.go
  pkg/cmd/kore/kore.go
  pkg/cmd/utils/handler.go
  pkg/cmd/utils/helper.go
  pkg/cmd/utils/wait.go
  pkg/utils/kubernetes/runtime_objects.go
Labels: cleanup

#884 Fixup - Plan viewer not working correctly from plan list
  ui/lib/components/plans/PlanList.js
  ui/lib/components/resources/ResourceList.js
Labels: bug

#880 Add service platform label to servicekinds + sort out cloud vs provider names in the UI code
  pkg/apiclient/operations/list_service_kinds_parameters.go
  pkg/apiserver/service_kinds.go
  pkg/cmd/kore/get/get.go
  pkg/cmd/kore/get/servicekind.go
  pkg/cmd/utils/resource_types.go
  pkg/kore/korefakes/fake_service_kinds.go
  pkg/kore/service_kinds.go
  pkg/serviceproviders/application/provider.go
  pkg/serviceproviders/awsservicebroker/factory.go
  pkg/serviceproviders/dummy.go
  pkg/serviceproviders/openservicebroker/factory.go
  pkg/serviceproviders/openservicebroker/provider.go
  pkg/serviceproviders/openservicebroker/provider_test.go
  pkg/serviceproviders/openservicebroker/types.go
  ui/__tests__/unit/lib/components/teams/cluster/ClusterBuildForm.test.js
  ui/config.js
  ui/config.public.js
  ui/kore-api-swagger.json
  ui/lib/components/common/CloudSelector.js
  ui/lib/components/plans/ManageClusterPlanForm.js
  ui/lib/components/resources/ResourceList.js
  ui/lib/components/services/CloudServiceAdmin.js
  ui/lib/components/services/ServiceKindList.js
  ui/lib/components/setup/ExistingCloudAccounts.js
  ui/lib/components/setup/GCPProjectAutomationSettings.js
  ui/lib/components/setup/forms/RequestCredentialAccessForm.js
  ui/lib/components/teams/cluster/ClusterBuildForm.js
  ui/lib/components/teams/cluster/ClusterOptionsForm.js
  ui/lib/components/teams/cluster/MissingCredential.js
  ui/lib/components/teams/service/ServiceBuildForm.js
  ui/lib/prototype/components/common/CloudSelector.js
  ui/lib/prototype/components/configure/ProjectAutomationSettings.js
  ui/lib/prototype/components/teams/service/ServiceForm.js
  ui/lib/utils/crd-helpers.js
  ui/pages/prototype/setup/kore/cloud-access.js
  ui/pages/setup/kore/cloud-access.js
Labels: EPIC: AWS Cloud Services, cleanup
